{-# LANGUAGE CPP #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif
{-# LANGUAGE FlexibleInstances #-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for PrintGrammar.
--   Generated by the BNF converter.

module PrintGrammar where

import qualified AbsGrammar
import Data.Char

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else ' ':s)

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsGrammar.Id where
  prt _ (AbsGrammar.Id i) = doc (showString i)
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsGrammar.Program where
  prt i e = case e of
    AbsGrammar.PDefs uses defs -> prPrec i 0 (concatD [prt 0 uses, prt 0 defs])

instance Print AbsGrammar.Use where
  prt i e = case e of
    AbsGrammar.UDef class_ -> prPrec i 0 (concatD [doc (showString "using"), prt 0 class_])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print AbsGrammar.Def where
  prt i e = case e of
    AbsGrammar.DFun type_ id args stms -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "{"), prt 0 stms, doc (showString "}")])
  prtList _ [] = concatD []
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [AbsGrammar.Use] where
  prt = prtList

instance Print [AbsGrammar.Def] where
  prt = prtList

instance Print AbsGrammar.Arg where
  prt i e = case e of
    AbsGrammar.ADecl type_ id -> prPrec i 0 (concatD [prt 0 type_, prt 0 id])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsGrammar.Arg] where
  prt = prtList

instance Print AbsGrammar.Stm where
  prt i e = case e of
    AbsGrammar.SExp exp -> prPrec i 0 (concatD [prt 0 exp, doc (showString ";")])
    AbsGrammar.SDecls type_ ids -> prPrec i 0 (concatD [prt 0 type_, prt 0 ids, doc (showString ";")])
    AbsGrammar.SInit type_ id exp -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, doc (showString "="), prt 0 exp, doc (showString ";")])
    AbsGrammar.SReturn exp -> prPrec i 0 (concatD [doc (showString "return"), prt 0 exp, doc (showString ";")])
    AbsGrammar.SReturnVoid -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    AbsGrammar.SWhile exp stm -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm])
    AbsGrammar.SFor exp1 exp2 exp3 stm -> prPrec i 0 (concatD [doc (showString "for"), doc (showString "("), prt 0 exp1, doc (showString ";"), prt 0 exp2, doc (showString ";"), prt 0 exp3, doc (showString ")"), prt 0 stm])
    AbsGrammar.SBlock stms -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stms, doc (showString "}")])
    AbsGrammar.SIfElse exp stm1 stm2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm1, doc (showString "else"), prt 0 stm2])
    AbsGrammar.SIf exp stm -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm])
    AbsGrammar.SThrow exp -> prPrec i 0 (concatD [doc (showString "throw"), prt 0 exp, doc (showString ";")])
    AbsGrammar.STypeDef class_ id -> prPrec i 0 (concatD [doc (showString "typedef"), prt 0 class_, prt 0 id, doc (showString ";")])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [AbsGrammar.Stm] where
  prt = prtList

instance Print AbsGrammar.Exp where
  prt i e = case e of
    AbsGrammar.EId id -> prPrec i 15 (concatD [prt 0 id])
    AbsGrammar.EAppApp id exp -> prPrec i 15 (concatD [prt 0 id, doc (showString "."), prt 15 exp])
    AbsGrammar.EApp id exps -> prPrec i 15 (concatD [prt 0 id, doc (showString "("), prt 0 exps, doc (showString ")")])
    AbsGrammar.ClassDefId classi -> prPrec i 15 (concatD [prt 0 classi])
    AbsGrammar.ETrue -> prPrec i 15 (concatD [doc (showString "true")])
    AbsGrammar.EFalse -> prPrec i 15 (concatD [doc (showString "false")])
    AbsGrammar.EInt n -> prPrec i 15 (concatD [prt 0 n])
    AbsGrammar.EDouble d -> prPrec i 15 (concatD [prt 0 d])
    AbsGrammar.EString str -> prPrec i 15 (concatD [prt 0 str])
    AbsGrammar.EWeird str1 str2 -> prPrec i 15 (concatD [prt 0 str1, prt 0 str2])
    AbsGrammar.EPIncr exp -> prPrec i 14 (concatD [prt 15 exp, doc (showString "++")])
    AbsGrammar.EPDecr exp -> prPrec i 14 (concatD [prt 15 exp, doc (showString "--")])
    AbsGrammar.EIncr exp -> prPrec i 13 (concatD [doc (showString "++"), prt 14 exp])
    AbsGrammar.EDecr exp -> prPrec i 13 (concatD [doc (showString "--"), prt 14 exp])
    AbsGrammar.ETimes exp1 exp2 -> prPrec i 12 (concatD [prt 12 exp1, doc (showString "*"), prt 13 exp2])
    AbsGrammar.EDiv exp1 exp2 -> prPrec i 12 (concatD [prt 12 exp1, doc (showString "/"), prt 13 exp2])
    AbsGrammar.EPlus exp1 exp2 -> prPrec i 11 (concatD [prt 11 exp1, doc (showString "+"), prt 12 exp2])
    AbsGrammar.EMinus exp1 exp2 -> prPrec i 11 (concatD [prt 11 exp1, doc (showString "-"), prt 12 exp2])
    AbsGrammar.ELs exp1 exp2 -> prPrec i 10 (concatD [prt 10 exp1, doc (showString "<<"), prt 0 exp2])
    AbsGrammar.ERs exp1 exp2 -> prPrec i 10 (concatD [prt 10 exp1, doc (showString ">>"), prt 0 exp2])
    AbsGrammar.ELt exp1 exp2 -> prPrec i 9 (concatD [prt 9 exp1, doc (showString "<"), prt 10 exp2])
    AbsGrammar.EGt exp1 exp2 -> prPrec i 9 (concatD [prt 9 exp1, doc (showString ">"), prt 10 exp2])
    AbsGrammar.ELtEq exp1 exp2 -> prPrec i 9 (concatD [prt 9 exp1, doc (showString "<="), prt 10 exp2])
    AbsGrammar.EGtEq exp1 exp2 -> prPrec i 9 (concatD [prt 9 exp1, doc (showString ">="), prt 10 exp2])
    AbsGrammar.EEq exp1 exp2 -> prPrec i 8 (concatD [prt 8 exp1, doc (showString "=="), prt 9 exp2])
    AbsGrammar.ENEq exp1 exp2 -> prPrec i 8 (concatD [prt 8 exp1, doc (showString "!="), prt 9 exp2])
    AbsGrammar.EAnd exp1 exp2 -> prPrec i 4 (concatD [prt 4 exp1, doc (showString "&&"), prt 5 exp2])
    AbsGrammar.EOr exp1 exp2 -> prPrec i 3 (concatD [prt 3 exp1, doc (showString "||"), prt 4 exp2])
    AbsGrammar.EAss exp1 exp2 -> prPrec i 2 (concatD [prt 3 exp1, doc (showString "="), prt 2 exp2])
    AbsGrammar.ETyped exp type_ -> prPrec i 15 (concatD [doc (showString "("), prt 0 exp, doc (showString ":"), prt 0 type_, doc (showString ")")])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsGrammar.Type where
  prt i e = case e of
    AbsGrammar.TypeDef id type_ -> prPrec i 0 (concatD [prt 0 id, doc (showString "<"), prt 0 type_, doc (showString ">")])
    AbsGrammar.ConstType type_ -> prPrec i 0 (concatD [doc (showString "const"), prt 0 type_, doc (showString "&")])
    AbsGrammar.ClassDefTy classt -> prPrec i 0 (concatD [prt 0 classt])
    AbsGrammar.Type_bool -> prPrec i 0 (concatD [doc (showString "bool")])
    AbsGrammar.Type_int -> prPrec i 0 (concatD [doc (showString "int")])
    AbsGrammar.Type_double -> prPrec i 0 (concatD [doc (showString "double")])
    AbsGrammar.Type_void -> prPrec i 0 (concatD [doc (showString "void")])
    AbsGrammar.Type_string -> prPrec i 0 (concatD [doc (showString "string")])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsGrammar.ClassI where
  prt i e = case e of
    AbsGrammar.ClassDef1 id1 id2 -> prPrec i 0 (concatD [prt 0 id1, doc (showString "::"), prt 0 id2])
    AbsGrammar.ClassRDef1 class_ id -> prPrec i 0 (concatD [prt 0 class_, doc (showString "::"), prt 0 id])

instance Print AbsGrammar.ClassT where
  prt i e = case e of
    AbsGrammar.ClassDef2 id type_ -> prPrec i 0 (concatD [prt 0 id, doc (showString "::"), prt 0 type_])
    AbsGrammar.ClassRDef2 class_ type_ -> prPrec i 0 (concatD [prt 0 class_, doc (showString "::"), prt 0 type_])

instance Print AbsGrammar.Class where
  prt i e = case e of
    AbsGrammar.CDefI classi -> prPrec i 0 (concatD [prt 0 classi])
    AbsGrammar.CDefT classt -> prPrec i 0 (concatD [prt 0 classt])

instance Print [AbsGrammar.Exp] where
  prt = prtList

instance Print [AbsGrammar.Id] where
  prt = prtList

instance Print [AbsGrammar.Type] where
  prt = prtList

